SELECT * FROM EMPLOYEES

select first_name, last_name from EMPLOYEES

1) Display the
details of all employees 






SQL :Select * from employees 
2) Display the depart information from
department table 



 



3) Display the name and job for all the
employees 



 



4) Display the name and salary  for all the employees 



 



5) Display the employee no and
totalsalary  for all the employees 



 



6) Display the employee name and annual
salary for all employees. 



 



7) Display the names of all the employees
who are working in depart number 10. 



 



8) Display the names of all the employees
who are working as clerks and  drawing
a salary more than 3000. 



   



9) Display the employee number and
name  who are earning comman salalry



 



10) Display the employee number and
name  who do not earn any common salary
